[tools]
actionlint = "1.7.10"
ghalint = "1.5.4"
"github:yuzutech/kroki-cli" = "latest"
hadolint = "latest"
node = "24.12.0"
pnpm = "10.27"
yamllint = "1.37.1"
zizmor = "1.20.0"

[env]
KROKI_ENDPOINT = "http://localhost:8000"
